### ISSUE TITLE
PREREQ_PM version for MojoX::NetstringStream too low

### ISSUE THREAD

**Issue by eserte** [a6502/JobCenter-Client-Mojo#6]
The test suite fails if MojoX::NetstringStream 0.04 is installed:
```
#   Failed test 'use JobCenter::Client::Mojo;'
#   at t/00-load.t line 7.
#     Tried to use 'JobCenter::Client::Mojo'.
#     Error:  MojoX::NetstringStream version 0.05 required--this is only version 0.04 at /usr/home/cpansand/.cpan/build/2017111615/JobCenter-Client-Mojo-0.29-7/blib/lib/JobCenter/Client/Mojo.pm line 35.
# BEGIN failed--compilation aborted at /usr/home/cpansand/.cpan/build/2017111615/JobCenter-Client-Mojo-0.29-7/blib/lib/JobCenter/Client/Mojo.pm line 35.
# Compilation failed in require at t/00-load.t line 7.
# BEGIN failed--compilation aborted at t/00-load.t line 7.
# Looks like you failed 1 test of 1.
t/00-load.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
```

**Comment by a6502** [comment]
I already uploaded JobCenter::Client::Mojo 0.30 with fixed requirements an 
hour ago.. ;)

Gr,

Wieger

On Thu, 16 Nov 2017, Slaven Rezić wrote:

> 
> The test suite fails if MojoX::NetstringStream 0.04 is installed:
> 
> #   Failed test 'use JobCenter::Client::Mojo;'
> #   at t/00-load.t line 7.
> #     Tried to use 'JobCenter::Client::Mojo'.
> #     Error:  MojoX::NetstringStream version 0.05 required--this is only version 0.04 at /usr/home/cpansand/.cpan/build/20171116
> 15/JobCenter-Client-Mojo-0.29-7/blib/lib/JobCenter/Client/Mojo.pm line 35.
> # BEGIN failed--compilation aborted at /usr/home/cpansand/.cpan/build/2017111615/JobCenter-Client-Mojo-0.29-7/blib/lib/JobCenter
> /Client/Mojo.pm line 35.
> # Compilation failed in require at t/00-load.t line 7.
> # BEGIN failed--compilation aborted at t/00-load.t line 7.
> # Looks like you failed 1 test of 1.
> t/00-load.t .. 
> Dubious, test returned 1 (wstat 256, 0x100)
> Failed 1/1 subtests 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.[AFbd7mWRCx6BR-pZPgBHaY2xf6m6Q-LZks5s3IfxgaJpZM4Qg-2z.gif]
> 
> 
>

~~
   Wieger

-- 
There's no time like Guinness time..
